import Head from "next/head";
import React, { FC } from "react";

type Props = React.DetailedHTMLProps<
  React.HTMLAttributes<HTMLDivElement>,
  HTMLDivElement
>;

export const Page: FC<Props> = ({ title, children, ...rest }) => {
  return (
    <>
      <Head>
        <title>{`Poke app${title ? `@${title}` : ""}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div {...rest}>{children}</div>
    </>
  );
};
