import Head from "next/head";
import React, { FC } from "react";

interface Props
  extends React.DetailedHTMLProps<
    React.HTMLAttributes<HTMLElement>,
    HTMLElement
  > {
  title?: string;
}

export const Page: FC<Props> = ({ title, children, ...rest }) => {
  return (
    <>
      <Head>
        <title>{title || "Poke app"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main {...rest}>{children}</main>
    </>
  );
};
